chatApi:
  chatApiToken: "<token>"
  providerId: "<id>"
  useChatApi: true
  baseUrl: "https://<account>.planfix.com/webchat/api"

webhook:
  enabled: false
  url: "https://example.com/hook"
  token: "<token>"
  skipPlanfixApi: false

proxyUrl: "http://localhost:8080"

leadTaskFields:
  - id: "456"
    name: "id сделки"
    argName: lead_id
    type: number

contactFields:
  - id: "123"
    name: "Резидентство"
    argName: resident
    type: enum
    values: ["резидент", "нерезидент", "иное"]

userFields:
  - id: "789"
    name: "Департамент"
    argName: department
    type: string
